# permissions to do viewer configmapreplicas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmapreplica-viewer-role
rules:
- apiGroups:
  - replica.example.com
  resources:
  - configmapreplicas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replica.example.com
  resources:
  - configmapreplicas/status
  verbs:
  - get
